# Generated by Django 5.1.2 on 2024-10-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='code',
            new_name='codigo',
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('cliente', 'codigo')},
        ),
    ]
