# Generated by Django 5.1.2 on 2024-10-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nombre_articulo_descripcion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='unique_articulo_cliente'),
        ),
    ]
