# Generated by Django 5.1.2 on 2024-10-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_articulo_unique_articulo_cliente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulo',
            name='unique_articulo_cliente',
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='unique_articulo_cliente', violation_error_message='El codigo del articulo ya existe para este cliente'),
        ),
    ]
