services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            - DB_HOST=db
            - DB_NAME=ait_db
            - DB_USER=ait_user
            - DB_PASSWORD=ait_password
        volumes:
            - ./backend:/app
        links:
            - db

    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        volumes:
            - ./frontend:/app

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ait_db
            MYSQL_USER: ait_user
            MYSQL_PASSWORD: ait_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db_data:
